title: Lester Thomas blog
author: Lester Thomas
email: lester.thomas@vodafone.com
description: > # this means to ignore newlines until "baseurl:"
  Lester Thomas blogs.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
